feeds:
  - url: https://feeds.bbci.co.uk/news/uk/rss.xml
    name: bbc-uk
  - url: http://feeds.bbci.co.uk/news/world/rss.xml
    name: bbc-world
  - url: https://www.theguardian.com/uk/rss
    name: the-guardian-uk
  - url: https://www.theguardian.com/world/rss
    name: the-guardian-world
  - url: https://blog.rust-lang.org/feed.xml
    name: rust-blog
  - url: https://blog.rust-lang.org/inside-rust/feed.xml
    name: inside-rust-blog
  - url: https://ziglang.org/news/index.xml
    name: zig
  - url: https://neovim.io/news.xml
    name: neovim
  - url: https://dotfyle.com/this-week-in-neovim/rss.xml
    name: this-week-in-neovim
  - url: https://weekly.nixos.org/feeds/all.rss.xml
    name: nixos-weekly
  - url: https://www.reddit.com/r/theprimeagen/.rss
    name: primeagen
  - url: https://fasterthanli.me/index.xml
    name: fasterthanlime
