"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
${custom.ls-shell}\
$username\
$directory \
"""

right_format = "$git_branch $time"

[username]
show_always = true
disabled = false
style_user = "bg:#51576d fg:#a5adce"
style_root = "bg:#51576d fg:#a5adce"
format = '[](bg:prev_bg fg:#51576d inverted)[ $user ]($style)'

[directory]
style = "fg:#51576d bg:#a6d189"
format = "[](bg:prev_bg fg:#a6d189 inverted)[ $path ]($style)[](fg:prev_bg)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "fg:#a5adce"
format = '[$symbol$branch]($style)'

[time]
disabled = false
style = "fg:#a5adce"
time_format = '%I:%M:%S %P'
format = '[$time]($style)'

[custom.ls-shell]
when = true
command = "exec ~/scripts/ls-current-shells"
style = "fg:#a5adce"
format = '[ $output ]($style)'
