"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
 $shell${env_var.SHLVL} \
$username \
$directory \
"""

right_format = "$git_branch $time"

[username]
show_always = true
disabled = false
style_user = "bg:#51576d fg:#a5adce"
style_root = "bg:#51576d fg:#a5adce"
format = '[](bg:prev_bg fg:#51576d)[ $user ]($style)[](fg:prev_bg)'

[directory]
style = "fg:#51576d bg:#a6d189"
format = "[](bg:prev_bg fg:#a6d189)[ $path ]($style)[](fg:prev_bg)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
style = "fg:#a5adce"
format = '[$symbol$branch]($style)'


[shell]
disabled = false
style = "bg:#51576d fg:#a5adce"
format = '[](bg:prev_bg fg:#51576d)[ $indicator ]($style)'

[env_var.SHLVL]
style = "bg:#51576d fg:#a5adce"
format = '[$env_value ]($style)[](fg:prev_bg)'
