# TODO: get email working

display-name = "Alan Randon"
signature = """
Thanks,
"""
signature-delim = """
-- 
"""
downloads-dir = "~/Downloads"

[accounts.outlook]
default = true
email = "alan.randon@outlook.com"
display-name = "Alan Randon"
downloads-dir = "/home/alan/Downloads"
backend.type = "imap"
backend.host = "outlook.office365.com"
backend.port = 993
backend.login = "alan.randon@outlook.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show outlook"
message.send.backend.type = "smtp"
message.send.backend.host = "smtp.office365.com"
message.send.backend.port = 587
message.send.backend.login = "alan.randon@outlook.com"
message.send.backend.encryption.type = "start-tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show outlook"

[account.list]
table.preset = "||  |-|||           "
table.name-color = "green"
table.backends-color = "blue"
table.default-color = "black"
