source = $HOME/.config/hypr/frappe.conf

$accent = $green
$accentAlpha = $greenAlpha
$font = FiraMono Nerd Font

# GENERAL
general {
  disable_loading_bar = true
  hide_cursor = true
  no_fade_in = true
}

# BACKGROUND
background {
  monitor =
  color = rgb(303446)
  path = /tmp/hyprlock-wallpaper
}

# Battery
label {
  monitor =
  text = cmd[update:5000] echo "  $(</sys/class/power_supply/BAT0/capacity)% $(tr '[:upper:]' '[:lower:]' </sys/class/power_supply/BAT0/status)"
  color = $text
  font_size = 30
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# TIME
label {
  monitor =
  text = cmd[update:1000] echo "<b>$(date +"%H:%M:%S")</b>"
  color = $text
  font_size = 30
  font_family = $font
  position = -30, -30
  halign = right
  valign = top
}

# INPUT FIELD
input-field {
  monitor =
  size = 600, 120
  outline_thickness = 10
  rounding = 0
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $crust
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -50
  halign = center
  valign = center
}

shape {
  size = 100%, 120
  halign = center
  valign = top
  color = $crust
}
