#!/usr/bin/env sh

swaymsg -mt subscribe '["window"]' \
	| jq -rc --unbuffered 'select(.change=="focus")' \
	| while read; do
		if $(swaymsg -t get_tree \
			| jq '.. | (.nodes? // empty)[] | select(.focused) | .rect.height > .rect.width')
		then
			swaymsg splitv
		else
			swaymsg splith
		fi
	  done
