#!/usr/bin/env sh

pkill -O 1 -f battery-notifier
while :; do
	capacity=$(cat /sys/class/power_supply/BAT0/capacity)
	status=$(cat /sys/class/power_supply/BAT0/status)
	if [[ $capacity -lt 20 && $status != "Charging" ]]; then
		notify-send "Battery Low" "$capacity%"
		sleep 60
	else
		sleep 10
	fi
done	
