#!/usr/bin/env sh

sources() {
	man -k . | awk '{ gsub(/[()]/,"",$2); print "man " $2 " " $1 }'
	# `tldr -u` to update source
	tldr -ql | awk '{ print "tldr \"" $1 "\"" }'
}

sources | fzf --bind 'enter:become(sh -c {})' --preview 'sh -c {}'
