#!/usr/bin/env sh

sources() {
# 	# `tldr -u` to update source
	tldr -ql | sed 's/^/TLDR - /'
	echo 'API - wttr.in/:help'
	echo 'API - cheat.sh/:help'
	echo 'API - https://check.torproject.org/api/ip'
	man -k . | sed 's/^/MAN - /'
	info -k . | sed 's/^/INFO - /'
	pydoc -k . | sed 's/^/PYDOC - /'
}

if [ -n "$1" ]; then
	man $@
	exit
fi

sources | fzf --bind "enter:become(
	if echo {} | grep -q 'MAN'; then
		echo {} | sed 's/MAN - //' | awk '{ gsub(/[()]/,\"\",\$2); print \$2 \" \" \$1 }' | xargs man
	elif echo {} | grep -q 'TLDR'; then
		echo {} | sed 's/TLDR - //' | xargs tldr | nvim '+Man!'
	elif echo \"{}\" | grep -q 'API'; then
		echo {} | sed 's/API - //' | xargs curl -s | nvim '+Man!'
	elif echo \"{}\" | grep -q 'PYDOC'; then
		echo {} | sed 's/PYDOC - \([^-]*\)\( - .*\)\{0,1\}/\1/' | xargs -I{} pydoc {} | nvim '+Man!'
	elif echo '{}' | grep -q 'INFO'; then
		~/scripts/fzfman-open-info-k {}
	fi
	)" 
