#!/usr/bin/env zsh

verbose=false

while getopts ':v' flag; do
  case "${flag}" in
    v) verbose='true' ;;
    *) echo "Usage: install-dotfiles [-v]"
       exit 1 ;;
  esac
done

cd "$(dirname $(realpath $0))/.."
mkdir -p ~/.config

xdg_cfgs=(
	nvim
	mpv
	waybar
	mako
	alacritty
	zathura
	newsboat
	hypr
	htop
	tridactyl
	starship.toml
	firefox/newtab.html
	bluetuith
	ghostty
	yazi
	glow
	neomutt
)

home_cfgs=(
	.zshrc
	.gitconfig
	.tmux.conf
	.npmrc
	scripts
)

desktop_cfgs=($(ls desktop/*.desktop))

for cfg in $xdg_cfgs
do
	loc=~/.config/$(basename $cfg)
	if [ -L $loc ] && [ "$(realpath "$loc")" = $(realpath $cfg) ]; then
		$verbose && echo Already linked: $loc
	elif [ -e $loc ]; then
		echo "Error (already exists): $loc -> $(realpath $loc)"
	else
		echo Linking: $loc
		ln -sT "$(realpath $cfg)" $loc
	fi
done

for cfg in $home_cfgs
do
	loc=~/$(basename $cfg)
	if [ -L $loc ] && [ "$(realpath "$loc")" = $(realpath $cfg) ]; then
		$verbose && echo Already linked: $loc
	elif [ -e $loc ]; then
		echo "Error (already exists): $loc -> $(realpath $loc)"
	else
		echo Linking: $loc
		ln -sT "$(realpath $cfg)" $loc
	fi
done

mkdir -p ~/.local/share/applications
ls /home/alan/.local/share/applications/*.desktop | xargs -I{} -n1 sh -c '[ ! -e {} ] && rm {} && echo Cleaned dead symlink: {}'
for cfg in $desktop_cfgs
do
	loc=~/.local/share/applications/$(basename $cfg)
	if [ -L $loc ] && [ "$(realpath "$loc")" = $(realpath $cfg) ]; then
		$verbose && echo Already linked: $loc
	elif [ -e $loc ]; then
		echo "Error (already exists): $loc -> $(realpath $loc)"
	else
		echo Linking: $loc
		ln -sT "$(realpath $cfg)" $loc
	fi
done

rg Path= <~/.mozilla/firefox/profiles.ini | cut -f2 -d= | while read profile; do
	chrome=~/.mozilla/firefox/$profile/chrome
	if [ -L $chrome ] && [ "$(realpath "$chrome")" = $(realpath ./firefox/chrome) ]; then
		$verbose && echo Already linked: $chrome
	elif [ -e $chrome ]; then
		echo "Error (already exists): $chrome -> $(realpath $chrome)"
	else
		echo Linking: $chrome
		ln -s -T "$(realpath ./firefox/chrome)" $chrome
	fi
done
