#!/usr/bin/env sh

cd "$(dirname $0)/.."

[ ! -d ~/.config/nvim ] && ln -st ~/.config "$(realpath ./nvim)"
[ ! -d ~/.config/bashmount ] && ln -st ~/.config "$(realpath ./bashmount)"
[ ! -d ~/.config/sway ] && ln -st ~/.config "$(realpath ./sway)"
[ ! -d ~/.config/swaylock ] && ln -st ~/.config "$(realpath ./swaylock)"
[ ! -d ~/.config/waybar ] && ln -st ~/.config "$(realpath ./waybar)"
[ ! -d ~/.config/mako ] && ln -st ~/.config "$(realpath ./mako)"
[ ! -d ~/.config/alacritty ] && ln -st ~/.config "$(realpath ./alacritty)"
[ ! -d ~/.config/zathura ] && ln -st ~/.config "$(realpath ./zathura)"
[ ! -d ~/.config/btop ] && ln -st ~/.config "$(realpath ./btop)"
[ ! -d ~/scripts ] && ln -st ~ "$(realpath ./scripts)"
[ ! -f ~/.zshrc ] && ln -s "$(realpath .zshrc)" ~/.zshrc 
[ ! -f ~/.tmux.conf ] && ln -s "$(realpath .tmux.conf)" ~/.tmux.conf  
[ ! -f ~/.config/starship.toml ] && ln -s "$(realpath starship.toml)" ~/.config/starship.toml
