#!/usr/bin/env sh

if (( $# != 2 )); then
	echo USAGE: mkflake TEMPLATE NAME
	exit 1
fi

template=$1
name=$2

if [[ -e ~/projects/$name ]]; then
	echo "~/projects/$name already exists"
	exit 1
fi

mkdir -p ~/projects/$name
session=$(~/scripts/tmux-sessionizer ~/projects/$name)
tmux send-keys -t $session:1.0 "nix flake init -t github:AlanRandon/nix-templates#$template" Enter
