#!/usr/bin/env zsh

if [ -z $1 ]; then
	ghostty -e ~/scripts/motd inner
	exit
fi

motd() {
	sleep 0.01
	hostname | figlet -cw $(tput cols) -f speed | clolcat
	curl "wttr.in/$(<~/scripts/motd-location)?format=3" -sm 1
	dysk
}

motd & while :; do
	read -sk1 shortcut
	case "${shortcut}"; in
		t) DISABLE_POPUP=true exec ~/scripts/tmux-sessionizer ;;
		b) hyprctl keyword exec '$browser' && exit ;;
		q) exit
	esac
done
