#!/usr/bin/env zsh

if [ -z $1 ]; then
	ghostty -e ~/scripts/motd inner
	exit
fi

center() {
	cols=$(tput cols)
	for line in $@; do
		echo $line 
	done | awk '{ padding = '$cols' - length; printf "%*s%s\n", padding / 2, "", $0 }'
}

motd() {
	fs=$(df -h / | tail -n1 | awk '{print $3 "/" $2 " (" $5 ")"}')
	glow <<(center "Storage: $fs" "" "[t]erminal" "[b]rowser" "[q]uit")
	curl "wttr.in/$(<~/scripts/motd-location)?0" -sm 1
}

msg=$(motd)

motd & while :; do
	read -sk1 shortcut
	case "${shortcut}"; in
		t) DISABLE_POPUP=true exec ~/scripts/tmux-sessionizer ;;
		b) hyprctl keyword exec '$browser' && exit ;;
		q) exit
	esac
done
