#!/usr/bin/env zsh

if [ -z $1 ]; then
	ghostty --background-opacity=0.7 -e ~/scripts/motd inner
	exit
fi

motd() {
	sleep 0.1
	hostname | figlet -cw $(tput cols) -f speed

	script -qfc "stty cols $(tput cols) rows $(tput lines); khal list today 7d; echo; df -h /" /dev/null | sed 's/^/\t\t/'
	echo
}

wait-for-lose-focus() {
	echo -ne "\e[?1004h" # listen for focus events
	while :; do
		read -sk3 event
		if [ $event = $(echo -e "\e[O") ]; then
			exit
		fi
	done
}

motd & wait-for-lose-focus
