#!/usr/bin/env sh

mpv_wrapper="$(command -v mpv)"

if [[ ! -f "$mpv_wrapper" ]]; then
    echo "mpv not found in PATH" >&2
    exit 1
fi

real_mpv="$(awk 'match($0, /"\/nix\/[^"]+mpv"/, m) {gsub(/"/,"",m[0]); print m[0]; exit}' "$mpv_wrapper")"

echo $real_mpv

if [[ -z "$real_mpv" || ! -x "$real_mpv" ]]; then
    echo "Failed to locate the real mpv binary" >&2
    exit 1
fi

exec "$real_mpv" "$@" 
