#!/usr/bin/env sh

ipc_socket="${XDG_RUNTIME_DIR:=/run/user/$UID}/mpv-music-ipc-socket"

selected=$(echo '{ "command": ["get_property", "playlist"] }' \
	| socat - "$ipc_socket" \
	| jq -r '.data | to_entries[] | "\(.key): \(.value.title // (.value.filename | sub(".*/"; "")))"' \
	| fuzzel --dmenu)

if [[ -z $selected ]]; then
	exit 0
fi

echo "{ \"command\": [\"set_property\", \"playlist-pos\", $(echo "$selected" | cut -d: -f1)] }" \
	| socat - "$ipc_socket"
