#!/usr/bin/env sh

human() {
    diff=$1
    if [ $diff -lt 60 ]; then
        printf "%s seconds ago" "$diff"
    elif [ $diff -lt 3600 ]; then
        printf "%s minutes ago" "$((diff/60))"
    elif [ $diff -lt 86400 ]; then
        printf "%s hours ago" "$((diff/3600))"
    else
        printf "%s days ago" "$((diff/86400))"
    fi
}

now=$(date +%s)

(
	echo -e "| Channel | Last Updated |\n| - | - |" \
	&& curl -s 'https://prometheus.nixos.org/api/v1/query?query=channel_update_time' \
	| jq -r '.data.result | sort_by(.value[1] | tonumber | -.)[] | "\(.metric.channel) \(.value[1])"' \
	| while read channel timestamp; do
		diff=$((now - ${timestamp%%.*}))
		echo "| $channel | $(human $diff) |"
	done
) | glow
