#!/usr/bin/env sh

if (( $# != 1 )); then
	echo USAGE: $0 PLAYLIST
	exit 1
fi

if [ "$1" = "-" ]; then
	playlist=/dev/stdin
else
	playlist="$1"
fi

xargs -d'\n' -I{} ffprobe -i {} -show_entries format=duration -v quiet -of csv='p=0' <$playlist \
	| paste -sd+ \
	| bc \
	| xargs -I{} date -d@{} -u +%H:%M:%S
