#!/usr/bin/env sh

usage() {
	echo "USAGE: $0 pull|push|usage"
	exit 1
}

push() {
	rclone copy ~/.abook/addressbook onedrive:abook -i
	rclone copy ~/.config/newsboat/urls onedrive:newsboat -i
	rclone sync ~/Pictures/wallpapers onedrive:wallpapers -i
	rclone sync ~/Music google-drive:Music -i
}

pull() {
	rclone copy onedrive:abook/addressbook ~/.abook/addressbook -i
	rclone copy onedrive:newsboat/urls ~/.config/newsboat/urls -i
	rclone sync onedrive:wallpapers ~/Pictures/wallpapers -i
	rclone sync google-drive:Music ~/Music -i
}

if (( $# != 1 )); then
	usage
fi

if [[ "$1" = "pull" ]]; then
	pull
elif [[ "$1" = "push" ]]; then
	push
elif [[ "$1" = "usage" ]]; then
	echo "=== Onedrive ==="
	rclone about onedrive:
	echo "=== Google Drive ==="
	rclone about google-drive:
else
	usage
fi
