#!/usr/bin/env zsh

[[ -z $DISABLE_POPUP ]] && FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --tmux 80%,80%"

DIRS=(
	'Documents'
	'Music'
	'projects'
	'projects/scratch'
	''
)

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(fd -Had1 -td . "${DIRS[@]/#/$HOME/}" | sed "s|^$HOME/||" \
		| fzf --tmux 80%,80% --preview-window top,border-none --preview '
		selected_name="$(basename {1} | tr . _)"
		if tmux has-session -t=$selected_name 2> /dev/null; then
			echo -e "\033[32msession running\033[0m"
			tmux list-windows -t=$selected_name
		else
			cd $HOME/{1}
			git -C . rev-parse 2>/dev/null && git log --oneline --color | head -n3
			eza --icons --git --tree --color=always
		fi
	')
	[[ $selected ]] && selected="$HOME/$selected"
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c $selected
	exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
	tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

echo $selected_name
